export const SQL_KEYWORDS = [
  'SELECT','FROM','WHERE','AND','OR','NOT','IN','BETWEEN','LIKE','IS','NULL',
  'ORDER','BY','GROUP','HAVING','LIMIT','OFFSET','AS','JOIN','LEFT','RIGHT',
  'INNER','OUTER','CROSS','ON','USING','UNION','ALL','DISTINCT','EXISTS',
  'INSERT','INTO','VALUES','UPDATE','SET','DELETE','CREATE','TABLE','DROP',
  'ALTER','ADD','COLUMN','INDEX','VIEW','TRIGGER','BEGIN','COMMIT','ROLLBACK',
  'TRANSACTION','PRAGMA','EXPLAIN','CASE','WHEN','THEN','ELSE','END','CAST',
  'ASC','DESC','PRIMARY','KEY','FOREIGN','REFERENCES','DEFAULT','CHECK',
  'UNIQUE','NOT','AUTOINCREMENT','IF','REPLACE','ABORT','FAIL','IGNORE',
  'RECURSIVE','WITH','EXCEPT','INTERSECT','VACUUM','REINDEX','ATTACH',
  'DETACH','GLOB','REGEXP','ESCAPE','COLLATE','INDEXED','TEMP','TEMPORARY',
];

export const SQL_FUNCTIONS = [
  'COUNT','SUM','AVG','MIN','MAX','TOTAL','GROUP_CONCAT',
  'ABS','COALESCE','IFNULL','IIF','NULLIF','TYPEOF','LIKELIHOOD',
  'LENGTH','SUBSTR','SUBSTRING','UPPER','LOWER','TRIM','LTRIM','RTRIM',
  'REPLACE','INSTR','HEX','QUOTE','UNICODE','CHAR','PRINTF','FORMAT',
  'DATE','TIME','DATETIME','JULIANDAY','STRFTIME','UNIXEPOCH',
  'RANDOM','RANDOMBLOB','ZEROBLOB','LAST_INSERT_ROWID','CHANGES',
  'TOTAL_CHANGES','SQLITE_VERSION','ROUND','JSON','JSON_EXTRACT',
];
